namespace ReadMeter.Api.Models;

public sealed class AereportEntity
{
    public string? ERPTID { get; set; }
    public DateTime? RPTDATE { get; set; }
    public string? RPTTIME { get; set; }
    public string? EXECUTER { get; set; }
    public string? RPTREASON { get; set; }
    public DateTime? DATECREATE { get; set; }
    public string? PRINTSTS { get; set; }
    public string? MNGOBJCOD { get; set; }
    public string? REPORTID { get; set; }
    public string? ERPTTYPE { get; set; }
    public string? ERPTSTS { get; set; }
    public string? CONID { get; set; }
    public string? RELATEID { get; set; }
    public string? USERNAME { get; set; }
    public DateTime? OPRTDATE { get; set; }
    public decimal? READCURR { get; set; }
    public decimal? TOTAL { get; set; }
    public string? SEALEMPNAME { get; set; }
    public DateTime? SEALDATE { get; set; }
    public string? SEALNO { get; set; }
    public DateTime? ERPTCYCLE { get; set; }
    public string? SEALCOD { get; set; }
    public string? CUSTID { get; set; }
    public string? CUSTNAME { get; set; }
    public string? CUSTADDR { get; set; }
    public string? CONADDR { get; set; }
    public string? CONTRACNO { get; set; }
    public string? METSERIAL { get; set; }
    public string? METKIND { get; set; }
    public string? METSIZE { get; set; }
    public string? CURRPURPOSE { get; set; }
    public string? NEWPURPOSE { get; set; }
    public long? CURRNORM { get; set; }
    public long? NEWNORM { get; set; }
    public DateTime? VALIDDATE { get; set; }
    public string? LOCATCOD { get; set; }
    public string? DEPOBJCOD { get; set; }
    public string? ERPTNO { get; set; }
    public decimal? READNUM { get; set; }
    public decimal? LASTREADNUM { get; set; }
    public string? ERPTCONTENT1 { get; set; }
    public string? ERPTCONTENT2 { get; set; }
    public string? ERPTCONTENT3 { get; set; }
    public string? EMPCOD { get; set; }
    public string? EMPNAME { get; set; }
    public string? ERPTONOFFTYPE { get; set; }
    public string? EREPORTTYPE { get; set; }
    public string? BOOKID { get; set; }
    public int? READSEAL { get; set; }
    public string? EMPREAD { get; set; }
    public string? EMPCOLLECT { get; set; }
    public decimal? TOTALPREV { get; set; }
    public decimal? TOTALCURR { get; set; }
}

public sealed class CcontractEntity
{
    public string? CONTRACID { get; set; }
    public string? CONTRACNO { get; set; }
    public DateTime? CONTRADATE { get; set; }
    public string? CUSTID { get; set; }
    public DateTime? CANCELDATE { get; set; }
    public string? CONTRATYPE { get; set; }
    public DateTime? PROCUDATE { get; set; }
    public string? PURCHAREPREID { get; set; }
    public int? NUMOFFAM { get; set; }
    public string? SUPPLYBNKACC { get; set; }
    public string? PROCUNO { get; set; }
    public string? PURCHASFAX { get; set; }
    public string? PURCHASOWN { get; set; }
    public string? SUPPLYOWN { get; set; }
    public DateTime? VALIDATIME { get; set; }
    public string? REQUESTID { get; set; }
    public string? SIGNEMPID { get; set; }
    public string? CONTRACSTS { get; set; }
    public string? MNGOBJCOD { get; set; }
    public string? REASONCOD { get; set; }
    public string? EMPCOD { get; set; }
    public string? SUPPLYBANKCOD { get; set; }
    public string? SUPPLYFNC { get; set; }
    public string? PURCHAFNC { get; set; }
    public string? PURCHAREF { get; set; }
    public string? SIGNFNC { get; set; }
    public string? CANCELREF { get; set; }
    public string? CPROCUNO { get; set; }
    public DateTime? CPROCUDATE { get; set; }
    public string? CPURCHAFNC { get; set; }
    public string? CPURCHAREF { get; set; }
    public string? MANAGECOD { get; set; }
    public string? OBJECTTYPE { get; set; }
    public string? USERNAME { get; set; }
    public DateTime? OPRTDATE { get; set; }
    public string? DIRECT { get; set; }
    public int? NUMOFPER { get; set; }
    public long? CAPACITY { get; set; }
    public string? CANCELFNC { get; set; }
    public DateTime? CONTRACCDATE { get; set; }
    public string? SUPPLYTAXID { get; set; }
    public string? SUPPLYTEL { get; set; }
    public string? SUPPLYADDR { get; set; }
    public string? PURCHARADDR { get; set; }
    public string? PURCHATEL { get; set; }
    public string? PURCHATAXID { get; set; }
    public string? PURCHABANKACC { get; set; }
    public DateTime? DATECREATE { get; set; }
    public string? POPULATIONNO { get; set; }
    public string? PURCHABANKCOD { get; set; }
    public DateTime? PURCHAREPREDATE { get; set; }
    public string? PURCHAREPRESOURCE { get; set; }
    public string? PURCHAPOPULATIONNO { get; set; }
    public string? ACCID { get; set; }
    public string? PURPOSE { get; set; }
    public string? CONTRACTTRANSTYPE { get; set; }
    public DateTime? CONTRACTTRANSDATE { get; set; }
    public string? OCCUCOD { get; set; }
    public string? OCCUCOD1 { get; set; }
    public string? OCCUCOD2 { get; set; }
    public string? OCCUCOD3 { get; set; }
    public string? CUSTNAME { get; set; }
    public string? CUSTADDR { get; set; }
    public string? CONADDR { get; set; }
    public string? LOCATCOD { get; set; }
    public string? METCATCOD { get; set; }
    public string? METKIND { get; set; }
    public string? METSIZE { get; set; }
    public string? METOWNER { get; set; }
    public string? TARIFFCOD { get; set; }
    public DateTime? TARIFFDATE { get; set; }
    public string? TARIFFSTR { get; set; }
    public string? TARIFFSTRE { get; set; }
    public string? MTAINCOD { get; set; }
    public string? ZONECODE { get; set; }
    public string? CUSTLOCATCOD { get; set; }
    public decimal? POCCUCOD { get; set; }
    public decimal? POCCUCOD1 { get; set; }
    public decimal? POCCUCOD2 { get; set; }
    public decimal? POCCUCOD3 { get; set; }
    public string? PURCHAPAYMENTMOD { get; set; }
    public string? CANCELNOTE { get; set; }
    public string? PURCHATEL1 { get; set; }
    public string? PURCHATEL2 { get; set; }
    public string? PURCHAEMAIL { get; set; }
    public string? PURCHAEMAIL1 { get; set; }
    public string? PURCHAEMAIL2 { get; set; }
    public string? PROCUAUTHORITY { get; set; }
    public string? CPROCUAUTHORITY { get; set; }
    public string? PREVMNGOBJCOD { get; set; }
}

